# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbvc', '0004_menu_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='路由别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbvc.Menu', verbose_name='所属菜单'),
            preserve_default=False,
        ),
    ]
